jobs:
  test:
    executor:
      name: node/default
      tag: '14.0'
    docker:
      - image: danlynn/ember-cli
    steps:
      - checkout
      - run:
          name: install
          command: npm install
      - run:
          name: tests
          command: npm run test
orbs:
  node: 'circleci/node@2.0.3'
version: 2.1
workflows:
  test_my_app:
    jobs:
      - test